version: '3.8'

services:
  go-database:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
    volumes:
      - go-database:/var/lib/postgresql/data
    networks: ['go-network']
  go-rest-api:
    image: go-rest-api
    container_name: backend-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - go-database
    networks: ['go-network']

volumes:
  go-database:
    driver: local

networks:
  go-network:
    driver: bridge
